version: "3.9"
services:
  frontend:
    image: carpet-frontend:latest
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
  #   depends_on:
  #     - backend
  # backend:
  db:
    image: carpet-db:latest
    build:
      context: ./db
    container_name: db
    env_file:
      - .env
    ports:
      - "3306:3306" #remove later, only backend will have access
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db