version: "3.9"
services:
  frontend:
    image: react:latest
    build:
      context: ./frontend
    container_name: react
    ports:
      - "3000:3000"
  #   depends_on:
  #     - backend
  # backend:
  # db: