version: "3.9"
services:
  frontend:
    image: carpet-frontend:latest
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
  #   depends_on:
  #     - backend
  # backend:
  # db: